web/project/user/forms.py
# project/user/forms.py

from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired, Email, Length, EqualTo
from project.model.user import Users

class LoginForm(FlaskForm):
    email = TextField('email', validators=[DataRequired(), Email()])
    password = PasswordField('password', validators=[DataRequired()])

class RegisterForm(FlaskForm):
    email = TextField('email', validators=[DataRequired(), Email(message=None), Length(min=6, max=255)])
    password = PasswordField('password', validators=[DataRequired(), Length(min=6, max=255)])
    confirm = PasswordField('Repeat password',validators=[DataRequired(),EqualTo('password', message='Passwords must match.')])

    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation: return False
        user = Users.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        else: return True

class ForgotForm(FlaskForm):
    email = TextField('email',validators=[DataRequired(), Email(message=None), Length(min=6, max=255)])

    def validate(self):
        initial_validation = super(ForgotForm, self).validate()
        if not initial_validation: return False
        user = Users.query.filter_by(email=self.email.data).first()
        if not user:
            self.email.errors.append("This email is not registered")
            return False
        else: return True

class ChangePasswordForm(FlaskForm):
    password = PasswordField('password', validators=[DataRequired(), Length(min=6, max=255)])
    confirm = PasswordField('Repeat password',validators=[DataRequired(),EqualTo('password', message='Passwords must match.')])

web/project/__init__.py
# project/__init__.py

#################
#### imports ####
#################
import os, warnings
from flask import Flask, render_template, request, redirect, flash, url_for
from flask_login import logout_user, LoginManager, login_user, current_user
from flask_bcrypt import Bcrypt
from flask_mail import Mail
from flask_debugtoolbar import DebugToolbarExtension
from flask_sqlalchemy import SQLAlchemy, get_debug_queries
from flask_admin import AdminIndexView, expose, helpers
from flask_admin.contrib.sqla import ModelView
from flask_cdn import CDN
from flask_compress import Compress

################
#### config ####
################

app = Flask(__name__)

try:
    APP_SET = os.environ['APP_SETTINGS']
    app.config.from_object("project.config."+APP_SET+"Config")
except KeyError:
    app.config.from_object("project.config.ProductionConfig") # Assume

####################
#### extensions ####
####################

login_manager = LoginManager()
login_manager.init_app(app)
bcrypt = Bcrypt(app)
mail = Mail(app)
toolbar = DebugToolbarExtension(app)
db = SQLAlchemy(app)
cdn = CDN(app)
Compress(app)

###############
#### cache ####
###############

from project.cache import cache

####################
#### blueprints ####
####################

from project.main.views import main_blueprint
from project.user.views import user_blueprint
app.register_blueprint(main_blueprint)
app.register_blueprint(user_blueprint)

#####################
#### flask-login ####
#####################
from wtforms import form, fields, validators
from project.model.user import Users
from werkzeug.security import check_password_hash

# Define login and registration forms (for flask-login)
class LoginForm(form.Form):
    email = fields.StringField(validators=[validators.required()])
    password = fields.PasswordField(validators=[validators.required()])

    def validate_email(self, field):
        user = self.get_user()
        if user is None: raise validators.ValidationError('Invalid email')
        if not bcrypt.check_password_hash(user.password, self.password.data): raise validators.ValidationError('Invalid password')

    def get_user(self):
        return db.session.query(Users).filter_by(email=self.email.data).first()

# Create customized model view class
class MyModelView(ModelView):
    def is_accessible(self):
        return current_user.is_authenticated

# Create customized index view class that handles login & registration
class MyAdminIndexView(AdminIndexView):
    @expose('/')
    def index(self):
        if not current_user.is_authenticated: return redirect(url_for('.login_view'))
        return super(MyAdminIndexView, self).index()

    @expose('/login/', methods=('GET', 'POST'))
    def login_view(self):
        # user login
        form = LoginForm(request.form)
        if helpers.validate_form_on_submit(form):
            user = form.get_user()
            login_user(user)

        if current_user.is_authenticated: return redirect(url_for('.index'))
        self._template_args['form'] = form
        return super(MyAdminIndexView, self).index()

    @expose('/logout/')
    def logout_view(self):
        logout_user()
        return redirect(url_for('.index'))


# Initialize flask-login
def init_login():
    login_manager = LoginManager()
    login_manager.init_app(app)

    # Create user loader function
    @login_manager.user_loader
    def load_user(user_id): return db.session.query(Users).get(user_id)

    @login_manager.unauthorized_handler
    def unauthorized_callback(): return redirect('/login?next=' + request.path)

# Initialize flask-login
init_login()

########################
#### error handlers ####
########################

@app.errorhandler(403)
@cache.cached(timeout=3600)
def forbidden_page(error):
    app.logger.info('Forbidden page - [{}] [{}]'.format(request.path, error))
    return render_template("errors/403.html"), 403

@app.errorhandler(404)
@cache.cached(timeout=3600)
def page_not_found(error):
    return render_template("errors/404.html"), 404

@app.errorhandler(500)
@cache.cached(timeout=3600)
def server_error_page(error):
    app.logger.warning('Server error - [] [{}]'.format(request.path, error))
    return render_template("errors/500.html"), 500

@app.after_request
def after_request(response):
    for query in get_debug_queries():
        if query.duration >= app.config['DATABASE_QUERY_TIMEOUT']:
            app.logger.warning("Database slow: {}\nParameters: {}\nDuration: {}s\nContext: {}".format(query.statement, query.parameters, query.duration, query.context))
    return response

web/project/main/views.py
# project/main/views.py

#################
#### imports ####
#################

import re
from flask import Blueprint, redirect, url_for, render_template, flash
from flask_login import current_user
from flask_login import login_required
from project.email import send_email
from project.model.title import Title, film_detail, pagination
from project.cache import cache

################
#### config ####
################

main_blueprint = Blueprint('main', __name__,)

################
#### routes ####
################

@main_blueprint.route('/')
@main_blueprint.route('/filter/<path:page_type>/<path:parameter>/<int:page_index>',methods=['GET'])
@cache.cached(timeout=30)
def home(page_type='page',page_index=1,parameter='n'):
    posts, page_total = pagination(page_index, page_type, parameter)
    return render_template('pagination/index.html',page_index=page_index, page_total=page_total, posts=posts, page_type=page_type, parameter=parameter)

@main_blueprint.route("/film/<string:slug>/")
@main_blueprint.route("/watchseries/<string:slug>/")
@cache.cached(timeout=30)
def title(slug):
    try: film_data = film_detail(slug)[0]
    except IndexError: return render_template('errors/404.html'), 404
    return render_template('/main/title.html',film_id=slug,film_data=film_data)

web/project/user/views.py
# project/user/views.py

#################
#### imports ####
#################

from flask import render_template, Blueprint, url_for, redirect, flash, request
from flask_login import login_user, logout_user, login_required, fresh_login_required, current_user

from project.model.user import Users
from project.email import send_email
from project.token import generate_confirmation_token, confirm_token
from project.decorators import check_confirmed
from project import db, bcrypt
from .forms import LoginForm, RegisterForm, ChangePasswordForm, ForgotForm
from project.cache import cache
import datetime

################
#### config ####
################

user_blueprint = Blueprint('user', __name__,)

################
#### routes ####
################

@user_blueprint.route('/register', methods=['GET', 'POST'])
@cache.cached(timeout=60)
def register():
    #print(request.form)
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = Users(email=form.email.data,password=form.password.data,confirmed=False)
        db.session.add(user)
        db.session.commit()

        token = generate_confirmation_token(user.email)
        confirm_url = url_for('user.confirm_email', token=token, _external=True)
        html = render_template('user/activate.html', confirm_url=confirm_url)
        subject = "Please confirm your email"
        send_email(user.email, subject, html)

        login_user(user, remember=True)

        flash('A confirmation email has been sent via email.', 'info')
        return redirect(url_for("user.unconfirmed"))

    return render_template('user/register.html', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
@cache.cached(timeout=60)
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, request.form['password']):
            login_user(user, remember=True)
            flash('Welcome back!', 'info')
            return redirect(url_for('main.home'))
        else:
            flash('Invalid email and/or password.', 'error')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out.', 'info')
    return redirect(url_for('user.login'))

@user_blueprint.route('/profile', methods=['GET', 'POST'])
@login_required
@check_confirmed
@cache.cached(timeout=30)
def profile():
    form = ChangePasswordForm(request.form)
    if form.validate_on_submit():
        user = Users.query.filter_by(email=current_user.email).first()
        if user:
            user.password = bcrypt.generate_password_hash(form.password.data)
            db.session.commit()
            flash('Password successfully changed.', 'info')
            return redirect(url_for('user.profile'))
        else:
            flash('Password change was unsuccessful.', 'error')
            return redirect(url_for('user.profile'))
    return render_template('user/profile.html', form=form)


@user_blueprint.route('/confirm/<token>')
@login_required
def confirm_email(token):
    if current_user.confirmed:
        flash('Account already confirmed. Please login.', 'info')
        return redirect(url_for('main.home'))
    email = confirm_token(token)
    user = Users.query.filter_by(email=current_user.email).first_or_404()
    if user.email == email:
        user.confirmed = True
        user.confirmed_on = datetime.datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('Account successfully confirmed! You are now logged in.', 'info')
    else:
        flash('The confirmation link is invalid or has expired.', 'error')
    return redirect(url_for('main.home'))


@user_blueprint.route('/unconfirmed')
@login_required
def unconfirmed():
    if current_user.confirmed: return redirect(url_for('main.home'))
    flash('Please confirm your account!', 'warning')
    return render_template('user/unconfirmed.html')


@user_blueprint.route('/resend')
@login_required
def resend_confirmation():
    token = generate_confirmation_token(current_user.email)
    confirm_url = url_for('user.confirm_email', token=token, _external=True)
    html = render_template('user/activate.html', confirm_url=confirm_url)
    subject = "Please confirm your email"
    send_email(current_user.email, subject, html)
    flash('A new confirmation email has been sent.', 'info')
    return redirect(url_for('user.unconfirmed'))

@user_blueprint.route('/forgot',  methods=['GET', 'POST'])
def forgot():
    form = ForgotForm(request.form)
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        token = generate_confirmation_token(user.email)
        user.password_reset_token = token
        db.session.commit()

        reset_url = url_for('user.forgot_new', token=token, _external=True)
        html = render_template('user/reset.html', username=user.email, reset_url=reset_url)
        subject = "Reset your password"
        send_email(user.email, subject, html)

        flash('A password reset email has been sent via email.', 'info')
        return redirect(url_for("main.home"))
    else: return render_template('user/forgot.html', form=form)


@user_blueprint.route('/forgot/new/<token>', methods=['GET', 'POST'])
def forgot_new(token):

    email = confirm_token(token)
    user = Users.query.filter_by(email=email).first_or_404()

    if user.password_reset_token is not None:
        form = ChangePasswordForm(request.form)
        if form.validate_on_submit():
            user = Users.query.filter_by(email=email).first()
            if user:
                user.password = bcrypt.generate_password_hash(form.password.data)
                user.password_reset_token = None
                db.session.commit()

                login_user(user)
                flash('Password successfully changed.', 'success')
                return redirect(url_for('user.profile'))
            else:
                flash('Password change was unsuccessful.', 'error')
                return redirect(url_for('user.profile'))
        else:
            flash('You can now change your password.', 'info')
            return render_template('user/forgot_new.html', form=form)
    else: flash('Cannot reset the password - invalid reset token.', 'error')

    return redirect(url_for('main.home'))

web/project/templates/_base.html
<!DOCTYPE html>
<html>

<head>
  <title>Watch Movies Online Free on Website</title>
  <!-- meta -->
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="robots" content="index,follow">
  <meta http-equiv="content-language" content="en">
  <meta name="description" content="Watch HD Movies Online For Free and Download the latest movies without Registration at Website">
  <meta name="keywords" content="watch hd movies, watch HD films, Hot new movies">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
  <!-- css -->
  <link href="{{url_for('static', filename='css/bootstrap.min.css')}}" rel="stylesheet">
  <link href="{{url_for('static', filename='css/main.css')}}" rel="stylesheet">
  <link href="{{url_for('static', filename='css/slide.css')}}" rel="stylesheet">
  <link href="{{url_for('static', filename='css/main-dark.css')}}" rel="stylesheet">
  <!-- js -->
  <script type="text/javascript" src="{{url_for('static', filename='js/jquery-1.9.1.min.js')}}"></script>
  <script type="text/javascript" src="{{url_for('static', filename='js/jquery.lazyload.min.js')}}"></script>
  <script type="text/javascript" src="{{url_for('static', filename='js/main.js')}}"></script>
  <script type="text/javascript" src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>

  <link rel="shortcut icon" href="{{url_for('static', filename='img/favicon.png')}}" type="image/x-icon">
  {% block css %}{% endblock %}
</head>

<body>

  {% include "navigation.html" %}

  <!-- main -->
  <div id="main">
    <div class="container">

      <!-- alert -->
      {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %} {% for category, message in messages %}
      <div class="alert alert-{{ category }}">
        {{ message }}
      </div>
      {% endfor %} {% endif %} {% endwith %}

      <!-- page template -->
      {% block content %}{% endblock %}

      <!-- error -->
      {% if error %}
      <div class="alert alert-warning"><strong>Error:</strong> {{ error }}</div>
      {% endif %}


    </div>
  </div>
  <!-- /main -->

  {% include "_footer.html" %} {% include "modal.html" %}
  <!-- scripts -->

  {% block js %}{% endblock %}

</body>

</html>

<script>
  $(".mobile-menu").click(function () {
    $("#menu").toggle();
  });
  $(".mobile-search").click(function () {
    $("#search").toggle();
  });
  /*
    function a() {
        $(this).find(".sub-container").css("display", "block")
    }

    function b() {
        $(this).find(".sub-container").css("display", "none")
    }

    $(function () {
        function a() {
            var a = $(this),
                b = a.find(".modal-dialog");
            a.css("display", "block"), b.css("margin-top", Math.max(0, ($(window).height() - b.height()) / 2))
        }
        $(".modal").on("show.bs.modal", a), $(window).on("resize", function () {
            $(".modal:visible").each(a)
        })
    });
    */
</script>

web/project/templates/_base2.html
<!DOCTYPE html>
<html>

<head>
  <title>Watch Movies Online Free on Website</title>
  <!-- meta -->
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="robots" content="index,follow">
  <meta http-equiv="content-language" content="en">
  <meta name="description" content="Watch HD Movies Online For Free and Download the latest movies without Registration at Website">
  <meta name="keywords" content="watch hd movies, watch HD films, Hot new movies">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
  <!-- css -->
  <link href="{{url_for('static', filename='css/bootstrap.min.css')}}" rel="stylesheet">
  <link href="{{url_for('static', filename='css/main.css')}}" rel="stylesheet">
  <link href="{{url_for('static', filename='css/slide.css')}}" rel="stylesheet">
  <link href="{{url_for('static', filename='css/main-dark.css')}}" rel="stylesheet">
  <!-- js -->
  <script type="text/javascript" src="{{url_for('static', filename='js/jquery-1.9.1.min.js')}}"></script>
  <script type="text/javascript" src="{{url_for('static', filename='js/jquery.lazyload.min.js')}}"></script>
  <script type="text/javascript" src="{{url_for('static', filename='js/main.js')}}"></script>
  <script type="text/javascript" src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>

  <link rel="shortcut icon" href="{{url_for('static', filename='img/favicon.png')}}" type="image/x-icon">
  {% block css %}{% endblock %}
</head>

<body>

  {% include "navigation.html" %}

  <!-- alert -->
  {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %} {% for category, message in messages %}
  <div class="alert alert-{{ category }}">
    {{ message }}
  </div>
  {% endfor %} {% endif %} {% endwith %}

  <!-- page template -->
  {% block content %}{% endblock %}

  <!-- error -->
  {% if error %}
  <div class="alert alert-warning"><strong>Error:</strong> {{ error }}</div>
  {% endif %}

  {% include "_footer.html" %} {% include "modal.html" %}
  <!-- scripts -->

  {% block js %}{% endblock %}

</body>

</html>

<script>
  $(".mobile-menu").click(function () {
    $("#menu").toggle();
  });
  $(".mobile-search").click(function () {
    $("#search").toggle();
  });
  /*
    function a() {
        $(this).find(".sub-container").css("display", "block")
    }

    function b() {
        $(this).find(".sub-container").css("display", "none")
    }

    $(function () {
        function a() {
            var a = $(this),
                b = a.find(".modal-dialog");
            a.css("display", "block"), b.css("margin-top", Math.max(0, ($(window).height() - b.height()) / 2))
        }
        $(".modal").on("show.bs.modal", a), $(window).on("resize", function () {
            $(".modal:visible").each(a)
        })
    });
    */
</script>

web/project/templates/_footer.html
<!--footer-->
<footer>
  <div id="footer">
    <div class="container">
      <div class="row">
        <!--
        <div class="col-lg-12 footer-one">
          <div class="footer-link">
            <h3 class="footer-link-head">Website</h3>

            <p><a title="Movies" href="/movie/filter">Movies</a></p>

            <p><a title="Top IMDb" href="/movie/topimdb">Top IMDb</a></p>

            <p><a title="DMCA" href="/site/dmca">DMCA</a></p>

            <p><a title="FAQ" href="/site/faq">FAQ</a></p>

            <p><a title="Advertising" href="/site/promote">Advertising</a></p>
          </div>
          <div class="footer-link">
            <h3 class="footer-link-head">Movies</h3>

            <p><a title="Action" href="/genre/action/">Action</a></p>

            <p><a title="History" href="/genre/history/">History</a></p>

            <p><a title="Thriller" href="/genre/thriller/">Thriller</a></p>

            <p><a title="Sci-Fi" href="/genre/sci-fi/">Sci-Fi</a></p>
          </div>
          <div class="footer-link end">
            <h3 class="footer-link-head">TV-Series</h3>

            <p><a title="United States" href="/movie/filter/series">United States</a></p>

            <p><a title="Korea" href="/movie/filter/series">Korea</a></p>

            <p><a title="China" href="/movie/filter/series">China</a></p>

            <p><a title="Taiwan" href="/movie/filter/series">Taiwan</a></p>
          </div>
        </div>
        -->
        <div class="col-lg-4 footer-copyright">
          <p><img id="logo-footer" border="0" src="{{url_for('static', filename='img/logo-light.png')}}" class="mv-ft-logo"></p>

          <p>Copyright © website.com - All Rights Reserved</p>

          <small class="grey">Disclaimer: This site does not store any files on its server. All contents are provided by non-affiliated third
            parties.</small>
        </div>
      </div>
      <!--
      <div class="footer-tags">
        <a title="Watch full movies online">Watch full movies online</a>
        <a title="Stream movies 2k online">Stream movies 2k online</a>
        <a title="Free films online">Free films online</a>
        <a title="Free online movies full">Free online movies full</a>
      </div>
      -->
    </div>
  </div>

</footer>
<!--/footer-->

web/project/templates/my_master.html
{% extends 'admin/base.html' %}

{% block access_control %}
{% if current_user.is_authenticated %}
<div class="btn-group pull-right">
    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="icon-user"></i> {{ current_user.login }} <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li><a href="{{ url_for('admin.logout_view') }}">Log out</a></li>
    </ul>
</div>
{% endif %}
{% endblock %}

web/project/templates/navigation.html
<!--header-->
<header style="position: fixed; top: 0px; background-color: rgb(255, 255, 255);">
  <div class="container">
    <div class="header-logo">

      <a title="Watch Your Favorite Movies Online" href="/" id="logo"></a>

    </div>

    <div class="mobile-menu"><i class="fa fa-reorder"></i></div>  
    <div class="mobile-search"><i class="fa fa-search"></i></div>
    <div id="menu">
      <ul class="top-menu">
        <li class="active">
          <a href="/" title="Home">HOME</a>
        </li>
        <li class="">
          <a href="/#" class="genre" title="Genre">GENRE</a>

          <div class="sub-container" style="display: none">
            <ul class="sub-menu">
              <li>
                <a href="/filter/genre/action/1">Action</a>
              </li>
              <li>
                <a href="/filter/genre/adventure/1">Adventure</a>
              </li>
              <li>
                <a href="/filter/genre/animation/1">Animation</a>
              </li>
              <li>
                <a href="/filter/genre/biography/1">Biography</a>
              </li>
              <li>
                <a href="/filter/genre/comedy/1">Comedy</a>
              </li>
              <li>
                <a href="/filter/genre/costume/1">Costume</a>
              </li>
              <li>
                <a href="/filter/genre/crime/1">Crime</a>
              </li>
              <li>
                <a href="/filter/genre/documentary/1">Documentary</a>
              </li>
              <li>
                <a href="/filter/genre/drama/1">Drama</a>
              </li>
              <li>
                <a href="/filter/genre/family/1">Family</a>
              </li>
              <li>
                <a href="/filter/genre/fantasy/1">Fantasy</a>
              </li>
              <li>
                <a href="/filter/genre/history/1">History</a>
              </li>
              <li>
                <a href="/filter/genre/horror/1">Horror</a>
              </li>
              <li>
                <a href="/filter/genre/kungfu/1">Kungfu</a>
              </li>
              <li>
                <a href="/filter/genre/musical/1">Musical</a>
              </li>
              <li>
                <a href="/filter/genre/mystery/1">Mystery</a>
              </li>
              <li>
                <a href="/filter/genre/mythological/1">Mythological</a>
              </li>
              <li>
                <a href="/filter/genre/psychological/1">Psychological</a>
              </li>
              <li>
                <a href="/filter/genre/romance/1">Romance</a>
              </li>
              <li>
                <a href="/filter/genre/sci-fi/1">Sci-Fi</a>
              </li>
              <li>
                <a href="/filter/genre/sitcom/1">Sitcom</a>
              </li>
              <li>
                <a href="/filter/genre/sport/1">Sport</a>
              </li>
              <li>
                <a href="/filter/genre/thriller/1">Thriller</a>
              </li>
              <li>
                <a href="/filter/genre/tv-show/1">TV Show</a>
              </li>
              <li>
                <a href="/filter/genre/war/1">War</a>
              </li>
            </ul>
          </div>
        </li>
        <li class="">
          <a href="/#" title="Country">COUNTRY</a>

          <div class="sub-container" style="display: none">
            <ul class="sub-menu">
              <li>
                <a href="/filter/country/Asia/1">Asia</a>
              </li>
              <li>
                <a href="/filter/country/China/1">China</a>
              </li>
              <li>
                <a href="/filter/country/Euro/1">Euro</a>
              </li>
              <li>
                <a href="/filter/country/France/1">France</a>
              </li>
              <li>
                <a href="/filter/country/HongKong/1">HongKong</a>
              </li>
              <li>
                <a href="/filter/country/India/1">India</a>
              </li>
              <li>
                <a href="/filter/country/Japan/1">Japan</a>
              </li>
              <li>
                <a href="/filter/country/Korea/1">Korea</a>
              </li>
              <li>
                <a href="/filter/country/Taiwan/1">Taiwan</a>
              </li>
              <li>
                <a href="/filter/country/Thailand/1">Thailand</a>
              </li>
              <li>
                <a href="/filter/country/United Kingdom/1">United Kingdom</a>
              </li>
              <li>
                <a href="/filter/country/United States/1">United States</a>
              </li>
            </ul>
          </div>
        </li>
        <li>
          <a href="/filter/type/series/1" title="TV - Series">TV - SERIES</a>
        </li>
        <li class="">
          <a href="#" title="Top IMDb">TOP IMDb</a>
        </li>
        <li class="">
          <a href="#" title="A-Z List">A - Z LIST</a>
        </li>
      </ul>
    </div>


    <div id="top-user">
      {% if current_user.is_authenticated %}
      <div class="top-user-content logged">
        <div class="logged-user">
          <a href="/#" class="avatar user-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img src="{{url_for('static', filename='img/default_avatar.jpg')}}">
            <i class="fa fa-chevron-down"></i>
          </a>
          <ul class="dropdown-menu">
            {% if current_user.confirmed %}
            <li><a href="{{ url_for('user.profile') }}"><i class="fa fa-user mr5"></i>Profile</a></li>
            {% else %}
            <li><a href="{{ url_for('user.unconfirmed') }}"><i class="fa fa-user mr5"></i>Confirm</a></li>
            {% endif %}
            <li><a href="{{ url_for('user.logout') }}"><i class="fa fa-power-off mr5"></i>Logout</a></li>
          </ul>
        </div>
      </div>
      {% elif not current_user.is_authenticated %}
      <div class="top-user-content guest">
        <a href="#" class="btn btn-successful btn-login" title="Login" data-target="#pop-login" data-toggle="modal">LOGIN</a>
      </div>
      {% endif %}
    </div>
    <div id="search">
      <div class="search-content">
        <input autofucus maxlength="100" autocomplete="off" name="keyword" type="text" class="form-control search-input" placeholder="Search...">
        <a onclick="searchMovie()" class="search-submit" href="javascript:void(0)" title="Search"><i class="fa fa-search"></i></a>

        <div class="search-suggest" style="display: none;"></div>
      </div>
    </div>
  </div>
</header>
<!--/header-->

web/project/templates/slider.html
<!-- slider -->
<div id="slider" class="swiper-container-horizontal">
    <div class="swiper-wrapper">

        <div class="swiper-slide" style="background-image: url(http://2.bp.blogspot.com/-RkQ3BeQ2qI0/WRaIdxXSKwI/AAAAAAAAcPs/y4TevRltbUQYQzoFiXOFoCbuLX8GTLtPwCK4B/s1600/banner.jpg);">
            <a href="/film/title/" class="slide-link" title="Title"></a>
            <span class="slide-caption">
                <h2>Title</h2>
                <p class="sc-desc">Description ...</p>
                <div class="slide-caption-info">
                    <div class="block"><strong>Genre:</strong>
                        <a href="/genre/genre/" title="Drama">genre</a>
                    </div>
                    <div class="block"><strong>Duration:</strong> 00 min</div>
                    <div class="block"><strong>Release:</strong> 2017</div>
                    <div class="block"><strong>IMDb:</strong> 7.8</div>
                </div>
            </span>
        </div>

    </div>
    <div class="swiper-pagination swiper-pagination-clickable"></div>
</div>

<script type="text/javascript" src="{{url_for('static', filename='js/slide.min.js')}}"></script>
<script>
    var swiper = new Swiper('#slider', {
        pagination: '.swiper-pagination',
        paginationClickable: true,
        loop: true,
        autoplay: 3000
    });
</script>
<!--/slider -->