web/project/user/forms.py
# project/user/forms.py

from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired, Email, Length, EqualTo
from project.model.user import Users

class LoginForm(FlaskForm):
    email = TextField('email', validators=[DataRequired(), Email()])
    password = PasswordField('password', validators=[DataRequired()])

class RegisterForm(FlaskForm):
    email = TextField('email', validators=[DataRequired(), Email(message=None), Length(min=6, max=255)])
    password = PasswordField('password', validators=[DataRequired(), Length(min=6, max=255)])
    confirm = PasswordField('Repeat password',validators=[DataRequired(),EqualTo('password', message='Passwords must match.')])

    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation: return False
        user = Users.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        else: return True

class ForgotForm(FlaskForm):
    email = TextField('email',validators=[DataRequired(), Email(message=None), Length(min=6, max=255)])

    def validate(self):
        initial_validation = super(ForgotForm, self).validate()
        if not initial_validation: return False
        user = Users.query.filter_by(email=self.email.data).first()
        if not user:
            self.email.errors.append("This email is not registered")
            return False
        else: return True

class ChangePasswordForm(FlaskForm):
    password = PasswordField('password', validators=[DataRequired(), Length(min=6, max=255)])
    confirm = PasswordField('Repeat password',validators=[DataRequired(),EqualTo('password', message='Passwords must match.')])

web/project/__init__.py
# project/__init__.py

#################
#### imports ####
#################
import os, warnings
from flask import Flask, render_template, request, redirect, flash, url_for
from flask_login import logout_user, LoginManager, login_user, current_user
from flask_bcrypt import Bcrypt
from flask_mail import Mail
from flask_debugtoolbar import DebugToolbarExtension
from flask_sqlalchemy import SQLAlchemy, get_debug_queries
from flask_admin import AdminIndexView, expose, helpers
from flask_admin.contrib.sqla import ModelView
from flask_cdn import CDN
from flask_compress import Compress

################
#### config ####
################

app = Flask(__name__)

try:
    APP_SET = os.environ['APP_SETTINGS']
    app.config.from_object("project.config."+APP_SET+"Config")
except KeyError:
    app.config.from_object("project.config.ProductionConfig") # Assume

####################
#### extensions ####
####################

login_manager = LoginManager()
login_manager.init_app(app)
bcrypt = Bcrypt(app)
mail = Mail(app)
toolbar = DebugToolbarExtension(app)
db = SQLAlchemy(app)
cdn = CDN(app)
Compress(app)

###############
#### cache ####
###############

from project.cache import cache

####################
#### blueprints ####
####################

from project.main.views import main_blueprint
from project.user.views import user_blueprint
app.register_blueprint(main_blueprint)
app.register_blueprint(user_blueprint)

#####################
#### flask-login ####
#####################
from wtforms import form, fields, validators
from project.model.user import Users
from werkzeug.security import check_password_hash

# Define login and registration forms (for flask-login)
class LoginForm(form.Form):
    email = fields.StringField(validators=[validators.required()])
    password = fields.PasswordField(validators=[validators.required()])

    def validate_email(self, field):
        user = self.get_user()
        if user is None: raise validators.ValidationError('Invalid email')
        if not bcrypt.check_password_hash(user.password, self.password.data): raise validators.ValidationError('Invalid password')

    def get_user(self):
        return db.session.query(Users).filter_by(email=self.email.data).first()

# Create customized model view class
class MyModelView(ModelView):
    def is_accessible(self):
        return current_user.is_authenticated

# Create customized index view class that handles login & registration
class MyAdminIndexView(AdminIndexView):
    @expose('/')
    def index(self):
        if not current_user.is_authenticated: return redirect(url_for('.login_view'))
        return super(MyAdminIndexView, self).index()

    @expose('/login/', methods=('GET', 'POST'))
    def login_view(self):
        # user login
        form = LoginForm(request.form)
        if helpers.validate_form_on_submit(form):
            user = form.get_user()
            login_user(user)

        if current_user.is_authenticated: return redirect(url_for('.index'))
        self._template_args['form'] = form
        return super(MyAdminIndexView, self).index()

    @expose('/logout/')
    def logout_view(self):
        logout_user()
        return redirect(url_for('.index'))


# Initialize flask-login
def init_login():
    login_manager = LoginManager()
    login_manager.init_app(app)

    # Create user loader function
    @login_manager.user_loader
    def load_user(user_id): return db.session.query(Users).get(user_id)

    @login_manager.unauthorized_handler
    def unauthorized_callback(): return redirect('/login?next=' + request.path)

# Initialize flask-login
init_login()

########################
#### error handlers ####
########################

@app.errorhandler(403)
@cache.cached(timeout=3600)
def forbidden_page(error):
    app.logger.info('Forbidden page - [{}] [{}]'.format(request.path, error))
    return render_template("errors/403.html"), 403

@app.errorhandler(404)
@cache.cached(timeout=3600)
def page_not_found(error):
    return render_template("errors/404.html"), 404

@app.errorhandler(500)
@cache.cached(timeout=3600)
def server_error_page(error):
    app.logger.warning('Server error - [] [{}]'.format(request.path, error))
    return render_template("errors/500.html"), 500

@app.after_request
def after_request(response):
    for query in get_debug_queries():
        if query.duration >= app.config['DATABASE_QUERY_TIMEOUT']:
            app.logger.warning("Database slow: {}\nParameters: {}\nDuration: {}s\nContext: {}".format(query.statement, query.parameters, query.duration, query.context))
    return response

web/project/main/views.py
# project/main/views.py

#################
#### imports ####
#################

import re
from flask import Blueprint, redirect, url_for, render_template, flash
from flask_login import current_user
from flask_login import login_required
from project.email import send_email
from project.model.title import Title, film_detail, pagination
from project.cache import cache

################
#### config ####
################

main_blueprint = Blueprint('main', __name__,)

################
#### routes ####
################

@main_blueprint.route('/')
@main_blueprint.route('/filter/<path:page_type>/<path:parameter>/<int:page_index>',methods=['GET'])
@cache.cached(timeout=30)
def home(page_type='page',page_index=1,parameter='n'):
    posts, page_total = pagination(page_index, page_type, parameter)
    return render_template('pagination/index.html',page_index=page_index, page_total=page_total, posts=posts, page_type=page_type, parameter=parameter)

@main_blueprint.route("/film/<string:slug>/")
@main_blueprint.route("/watchseries/<string:slug>/")
@cache.cached(timeout=30)
def title(slug):
    try: film_data = film_detail(slug)[0]
    except IndexError: return render_template('errors/404.html'), 404
    return render_template('/main/title.html',film_id=slug,film_data=film_data)

web/project/user/views.py
# project/user/views.py

#################
#### imports ####
#################

from flask import render_template, Blueprint, url_for, redirect, flash, request
from flask_login import login_user, logout_user, login_required, fresh_login_required, current_user

from project.model.user import Users
from project.email import send_email
from project.token import generate_confirmation_token, confirm_token
from project.decorators import check_confirmed
from project import db, bcrypt
from .forms import LoginForm, RegisterForm, ChangePasswordForm, ForgotForm
from project.cache import cache
import datetime

################
#### config ####
################

user_blueprint = Blueprint('user', __name__,)

################
#### routes ####
################

@user_blueprint.route('/register', methods=['GET', 'POST'])
@cache.cached(timeout=60)
def register():
    #print(request.form)
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = Users(email=form.email.data,password=form.password.data,confirmed=False)
        db.session.add(user)
        db.session.commit()

        token = generate_confirmation_token(user.email)
        confirm_url = url_for('user.confirm_email', token=token, _external=True)
        html = render_template('user/activate.html', confirm_url=confirm_url)
        subject = "Please confirm your email"
        send_email(user.email, subject, html)

        login_user(user, remember=True)

        flash('A confirmation email has been sent via email.', 'info')
        return redirect(url_for("user.unconfirmed"))

    return render_template('user/register.html', form=form)


@user_blueprint.route('/login', methods=['GET', 'POST'])
@cache.cached(timeout=60)
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, request.form['password']):
            login_user(user, remember=True)
            flash('Welcome back!', 'info')
            return redirect(url_for('main.home'))
        else:
            flash('Invalid email and/or password.', 'error')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out.', 'info')
    return redirect(url_for('user.login'))

@user_blueprint.route('/profile', methods=['GET', 'POST'])
@login_required
@check_confirmed
@cache.cached(timeout=30)
def profile():
    form = ChangePasswordForm(request.form)
    if form.validate_on_submit():
        user = Users.query.filter_by(email=current_user.email).first()
        if user:
            user.password = bcrypt.generate_password_hash(form.password.data)
            db.session.commit()
            flash('Password successfully changed.', 'info')
            return redirect(url_for('user.profile'))
        else:
            flash('Password change was unsuccessful.', 'error')
            return redirect(url_for('user.profile'))
    return render_template('user/profile.html', form=form)


@user_blueprint.route('/confirm/<token>')
@login_required
def confirm_email(token):
    if current_user.confirmed:
        flash('Account already confirmed. Please login.', 'info')
        return redirect(url_for('main.home'))
    email = confirm_token(token)
    user = Users.query.filter_by(email=current_user.email).first_or_404()
    if user.email == email:
        user.confirmed = True
        user.confirmed_on = datetime.datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('Account successfully confirmed! You are now logged in.', 'info')
    else:
        flash('The confirmation link is invalid or has expired.', 'error')
    return redirect(url_for('main.home'))


@user_blueprint.route('/unconfirmed')
@login_required
def unconfirmed():
    if current_user.confirmed: return redirect(url_for('main.home'))
    flash('Please confirm your account!', 'warning')
    return render_template('user/unconfirmed.html')


@user_blueprint.route('/resend')
@login_required
def resend_confirmation():
    token = generate_confirmation_token(current_user.email)
    confirm_url = url_for('user.confirm_email', token=token, _external=True)
    html = render_template('user/activate.html', confirm_url=confirm_url)
    subject = "Please confirm your email"
    send_email(current_user.email, subject, html)
    flash('A new confirmation email has been sent.', 'info')
    return redirect(url_for('user.unconfirmed'))

@user_blueprint.route('/forgot',  methods=['GET', 'POST'])
def forgot():
    form = ForgotForm(request.form)
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        token = generate_confirmation_token(user.email)
        user.password_reset_token = token
        db.session.commit()

        reset_url = url_for('user.forgot_new', token=token, _external=True)
        html = render_template('user/reset.html', username=user.email, reset_url=reset_url)
        subject = "Reset your password"
        send_email(user.email, subject, html)

        flash('A password reset email has been sent via email.', 'info')
        return redirect(url_for("main.home"))
    else: return render_template('user/forgot.html', form=form)


@user_blueprint.route('/forgot/new/<token>', methods=['GET', 'POST'])
def forgot_new(token):

    email = confirm_token(token)
    user = Users.query.filter_by(email=email).first_or_404()

    if user.password_reset_token is not None:
        form = ChangePasswordForm(request.form)
        if form.validate_on_submit():
            user = Users.query.filter_by(email=email).first()
            if user:
                user.password = bcrypt.generate_password_hash(form.password.data)
                user.password_reset_token = None
                db.session.commit()

                login_user(user)
                flash('Password successfully changed.', 'success')
                return redirect(url_for('user.profile'))
            else:
                flash('Password change was unsuccessful.', 'error')
                return redirect(url_for('user.profile'))
        else:
            flash('You can now change your password.', 'info')
            return render_template('user/forgot_new.html', form=form)
    else: flash('Cannot reset the password - invalid reset token.', 'error')

    return redirect(url_for('main.home'))

web/project/templates/user/activate.html
<link rel="stylesheet" href="{{url_for('static', filename='css/font/Montserrat.css')}}">
<div style="text-align: center;">

  <div style="display: block; font-family: 'Montserrat', sans-serif; font-weight: bold; color: #57607c; font-size: 25px; margin: 20px 0px 18px;">
    Account activation request
  </div>

  <div style="display: block; font-family: 'Montserrat', sans-serif; line-height: 25px; margin-bottom: 10px;">
    Click the following link to activate your account:
  </div>

  <a href="{{ confirm_url }}" target="_blank" style="background-color: #ebf2fa; color: #57607c; height: 30px; line-height: 30px; text-decoration: none; cursor: pointer; font-family: 'Montserrat', sans-serif; font-weight: bold; padding-left: 10px; padding-right: 10px; border-radius: 5px; font-size: 17px;">
    Activate account
  </a>

</div>

web/project/templates/user/forgot.html
{% extends "_base.html" %}
{% block content %}

<form role="form" method="post" action="">
  {{ form.csrf_token }}
	<div class="form text-center">

		<div class="bottom-10px">
      {{ form.email(placeholder="email",class="siimple-input center") }}
        {% if form.email.errors %}
					<label class="alert alert-warning center form-error top-10px">
          {% for error in form.email.errors %}
            {{ error }}
          {% endfor %}
					</label>
        {% endif %}
		</div>

    <input type="submit" value="Forgot password" class="siimple-btn siimple-btn--grey center bottom-10px form-button">

	</div>
</form>

{% endblock %}

web/project/templates/user/forgot_new.html
{% extends "_base.html" %}

{% block content %}

<h1>Forgot Your Password?</h1>
<br />
<form class="form-signin" role="form" method="post" action="">
  {{ form.csrf_token }}
  <p>
  {{ form.password(placeholder="password") }}
    <span class="error">
      {% if form.password.errors %}
        {% for error in form.password.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
  {{ form.confirm(placeholder="confirm") }}
    <span class="error">
      {% if form.confirm.errors %}
        {% for error in form.confirm.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <button class="btn btn-success" type="submit">Reset your password!</button>
  <br /><br />
</form>

{% endblock %}

web/project/templates/user/login.html
{% extends "_base.html" %}
{% block content %}

<form role="form" method="post" action="">
  {{ form.csrf_token }}
	<div class="form text-center">

		<div class="bottom-10px">
      {{ form.email(placeholder="email",class="siimple-input center") }}
        {% if form.email.errors %}
					<label class="alert alert-warning center form-error top-10px">
          {% for error in form.email.errors %}
            {{ error }}
          {% endfor %}
					</label>
        {% endif %}
		</div>

		<div class="bottom-10px">
		{{ form.password(placeholder="password",class="siimple-input center") }}
			{% if form.password.errors %}
				<label class="alert alert-warning center form-error top-10px">
				{% for error in form.password.errors %}
					{{ error }}
				{% endfor %}
				</label>
			{% endif %}
		</div>

    <input type="submit" value="Login" class="siimple-btn siimple-btn--grey center bottom-10px form-button">

		<div class="center">
			<div class="siimple-btn siimple-btn--navy form-button"><a href="/forgot" class="color-white">Forgot password</a></div>
		</div>

	</div>
</form>

{% endblock %}

web/project/templates/user/profile.html
{% extends "_base.html" %} {% block content %}{% if current_user.is_authenticated %}
<p><strong>{{current_user.email}}</strong></p>
{% if current_user.admin %}
<a href='/admin'>Admin</a>
{% endif %}
{% endif %}

<form role="form" method="post" action="">
	{{ form.csrf_token }}
	<div class="form text-center">

		<div class="bottom-10px">
			{{ form.password(placeholder="password",class="siimple-input center") }} {% if form.password.errors %}
			<label class="alert alert-warning center form-error top-10px">
				{% for error in form.password.errors %}
					{{ error }}
				{% endfor %}
				</label> {% endif %}
		</div>

		<div class="bottom-10px">
			{{ form.confirm(placeholder="confirm",class="siimple-input center") }} {% if form.confirm.errors %}
			<label class="alert alert-warning center form-error top-10px">
				{% for error in form.confirm.errors %}
					{{ error }}
				{% endfor %}
				</label> {% endif %}
		</div>

		<input type="submit" value="Change password" class="siimple-btn siimple-btn--grey center bottom-10px form-button">

	</div>
</form>

{% endblock %}

web/project/templates/user/register.html
{% extends "_base.html" %}
{% block content %}

<form role="form" method="post" action="">
  {{ form.csrf_token }}
	<div class="form text-center">

		<div class="bottom-10px">
      {{ form.email(placeholder="email",class="siimple-input center") }}
        {% if form.email.errors %}
					<label class="alert alert-warning center form-error top-10px">
          {% for error in form.email.errors %}
            {{ error }}
          {% endfor %}
					</label>
        {% endif %}
		</div>

		<div class="bottom-10px">
		{{ form.password(placeholder="password",class="siimple-input center") }}
			{% if form.password.errors %}
				<label class="alert alert-warning center form-error top-10px">
				{% for error in form.password.errors %}
					{{ error }}
				{% endfor %}
				</label>
			{% endif %}
		</div>

		<div class="bottom-10px">
		{{ form.confirm(placeholder="confirm",class="siimple-input center") }}
			{% if form.confirm.errors %}
				<label class="alert alert-warning center form-error top-10px">
				{% for error in form.confirm.errors %}
					{{ error }}
				{% endfor %}
				</label>
			{% endif %}
		</div>

    <input type="submit" value="Register" class="siimple-btn siimple-btn--grey center bottom-10px form-button">

	</div>
</form>

{% endblock %}

web/project/templates/user/reset.html
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
<div style="text-align: center;">

  <div style="display: block; font-family: 'Montserrat', sans-serif; font-weight: bold; color: #57607c; font-size: 25px; margin: 20px 0px 18px;">
    Password reset request
  </div>

  <div style="display: block; font-family: 'Montserrat', sans-serif; line-height: 25px; margin-bottom: 10px;">
    Click the following link to reset your password:
  </div>

  <a href="{{ reset_url }}" target="_blank" style="background-color: #ebf2fa; color: #57607c; height: 30px; line-height: 30px; text-decoration: none; cursor: pointer; font-family: 'Montserrat', sans-serif; font-weight: bold; padding-left: 10px; padding-right: 10px; border-radius: 5px; font-size: 17px;">
    Reset password
  </a>

</div>

web/project/templates/user/unconfirmed.html
{% extends "_base.html" %}

{% block content %}

<div class="siimple-p center">
  Please check your email (and spam folder) - you should have received an email with a confirmation link.<br />
  Didn't get the email?
  <div class="siimple-btn siimple-btn--navy center"><a href="{{ url_for('user.resend_confirmation') }}" class="color-white">Resend email</a></div>
</div>

{% endblock %}